### ISSUE TITLE
Add ENV VAR to expose --safe mode

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red-docker#102]
There is no easy way to run Node-RED in our docker image with safe mode enabled - because that can only be done via command-line arg.

We should provide a way to enable it via env var or other mechanism.

**Comment by Maddin-619** [comment]
There's a way even if it's not very beautiful:
`docker run -it -p 1880:1880 --entrypoint "/bin/bash" nodered/node-red-docker -c 'npm start -- --userDir /data --safe'`
Or in docker-compose file:
```
node-red:
  image: nodered/node-red-docker:latest
  ports:
    - "1880:1880"
  entrypoint: "npm start -- --userDir /data --safe"
```
