### ISSUE TITLE
Authentication is handled differently depending on container (slim vs regular)

### ISSUE THREAD

**Issue by rcarmo** [node-red/node-red-docker#109]
### What are the steps to reproduce?

I am trying to set up a `docker-compose` environment that takes the `bcrypt` hash as an environment variable and sets up authentication accordingly.

I have this YAML:

```yaml
 node-red:
        hostname: flows
        image: "nodered/node-red-docker:0.20.5-slim-v10" # https://hub.docker.com/r/nodered/node-red-docker/tags
        restart: always
        user: ${UID} # this needs to be set so that node-red can match filesystem UIDs
        environment:
            - ADMIN_AUTH
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /dev/rtc:/dev/rtc:ro
            - ${HOME}/.config/node-red:/data
        networks:
            - web
        #ports:
        #   - "1880:1880"
        labels:
            - "traefik.enable=true"
            - "traefik.backend=node-red"
            - "traefik.docker.network=web"
            - traefik.frontend.redirect.entryPoint=https
            - "traefik.frontend.rule=Host:flows.${DOMAIN_NAME}" # these will be read from .env
            - "traefik.port=1880"
```

...this `.env` file:

```bash
DOMAIN_NAME=foobar
ADMIN_AUTH=admin:bcrypt_hash
```

...which is filled in by this:

```bash
echo "ADMIN_AUTH=$(htpasswd -nB admin)" >> .env
```

...and this snippet in `settings.js` to get the hash from the container environment:

```javascript
    adminAuth: {
        type: "credentials",
        users: [{
            username: process.env.ADMIN_AUTH.slice(0,process.env.ADMIN_AUTH.indexOf(':')),
            password: process.env.ADMIN_AUTH.slice(process.env.ADMIN_AUTH.indexOf(':')+1),
            permissions: "*"
        }]
    },
```

### What happens?

This works if I use `nodered/node-red-docker:0.20.5-slim-v10` but **not** if I use `nodered/node-red-docker:0.20.5-v10`. I get an authentication failure.

### What do you expect to happen?

I expected either version of the container to be able to handle the exact same `bcrypt` hash. I have verified that the environment variable and hash are passed correctly to the container environment, but cannot figure out why the Node-RED version packed in `nodered/node-red-docker:0.20.5-v10` fails to validate the hash.

### Please tell us about your environment:

- [x] Node-RED version: 0.20.5-slim-v10
- [x] node.js version: the one packed into the container
- [x] npm version: the one packed into the container
- [x] Platform/OS: Ubuntu x86_64 as Docker host, whatever is in the container as userland
- [x] Browser: any
