### ISSUE TITLE
Unsupported version of Node.js from docker container official image

### ISSUE THREAD

**Issue by mauog** [node-red/node-red-docker#130]
I just pulled the new node-red container images from docker hub and I got this error:

```
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
nodered/node-red-docker   rpi-v8              e70abd5c40c4        17 hours ago        565MB
```

```
root@europa:~# docker logs nodered
npm info it worked if it ends with ok
npm info using npm@5.0.3
npm info using node@v8.1.3
npm info lifecycle node-red-docker@1.0.0~prestart: node-red-docker@1.0.0
npm info lifecycle node-red-docker@1.0.0~start: node-red-docker@1.0.0

> node-red-docker@1.0.0 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"

7 Sep 22:42:28 - [info] 

Welcome to Node-RED
===================

7 Sep 22:42:28 - [info] Node-RED version: v0.20.8
7 Sep 22:42:28 - [info] Node.js  version: v8.1.3
7 Sep 22:42:28 - [error] *****************************************************************
7 Sep 22:42:28 - [error] * Unsupported version of Node.js. Requires: >=8.9.0 Found: v8.1.3 *
7 Sep 22:42:28 - [error] *****************************************************************
7 Sep 22:42:28 - [info] Linux 4.19.34-v7+ arm LE
7 Sep 22:42:29 - [info] Loading palette nodes
7 Sep 22:42:35 - [info] Dashboard version 2.13.2 started at /ui


Is it possible to upgrade node.js from inside the container?

Thank You

Regards

**Comment by gluap** [comment]
@mauog I see the same, this is because the nodered rpi container is based on https://hub.docker.com/r/hypriot/rpi-node/ which is deprecated in favour of the now-official rpi nodejs containers provided by nodejs themselves.

**Comment by fightforlife** [comment]
So I think this would solve this issue:
https://github.com/node-red/node-red-docker/pull/127
#127

**Comment by IoTPlay** [comment]
Thank you, looks like the multi-architecture version will solve it. I see it is still open, but that you have passed most docker tests - i there a Tag that will work on RPi we can use already?

**Comment by nicedevil007** [comment]
or even how we can roll back to 0.20.7 until multi-architecture will work`?

**Comment by purnhar** [comment]
You can switch back yourself. Just use the docker image with tag 0.20.7-rpi-v8

**Comment by mauog** [comment]
Focusing on the functionality of the container I can see that it looks that all what is already configured still works fine but the UI is not completely due to the error message which cannot be moved or closed so you cannot access to all the tabs behind.

![Screenshot 2019-09-10 at 23 02 44](https://user-images.githubusercontent.com/36936293/64650373-4f3d4180-d41f-11e9-82c1-2f65ad0d2219.png)

**Comment by kpm-at-hfi** [comment]
Adding the text from that dialog so this issue is more easily findable:

> Using an unsupported version of Node.js
> 
> You should upgrade to the latest Node.js LTS release

**Comment by RaymondMouthaan** [comment]
Hi guys, i am the creator of PR #127, if you guys like to try node-red images which are based upon #127, i like to invite you to check out my [docker hub](https://cloud.docker.com/repository/docker/raymondmm/node-red/general).

How to use the images can be found in the [README](https://github.com/RaymondMouthaan/node-red-docker/blob/master/README.md)

**Comment by fightforlife** [comment]
I just tried your image as a dropin replacement for the rpi variant in docker compose.

```
version: "2"

services:

  nodered:
    image: raymondmm/node-red:latest
    #image: nodered/node-red-docker:rpi-v8
    container_name: nodered
    
    #Needed for WoL
    network_mode: "host" 
    #ports:
    #  - "9001:1880/tcp"
    
    
    restart: always
    volumes:
      - nodered_config:/data
      - nodered_cgroup:/sys/fs/cgroup
      - /sys:/sys
    devices:
      #- "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyS0:/dev/ttyS0"
      - "/dev/ttyS1:/dev/ttyS1"
      - "/dev/ttyS2:/dev/ttyS2"
      #- "/dev/gpiochip0:/dev/gpiochip0"
      #- "/dev/gpiochip1:/dev/gpiochip1"
      #- "/dev/i2c-1:/dev/i2c-1"
      #- "/dev/i2c-2:/dev/i2c-2"
      #- "/dev/i2c-3:/dev/i2c-3"
      #- "/dev/i2c-4:/dev/i2c-4"
    group_add:
      - dialout
    dns: 
      - 192.168.1.4
      - 192.168.1.3
      - 192.168.1.2
      - 192.168.1.1`
```

It doesnt seem to be fully compatible (permission problem):

```
> node-red-docker@1.0.0 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"
Welcome to Node-RED
===================
14 Sep 08:01:27 - [info] Node-RED version: v0.20.7
14 Sep 08:01:27 - [info] Node.js  version: v10.16.3
14 Sep 08:01:27 - [info] Linux 4.19.57-sunxi arm LE
14 Sep 08:01:30 - [info] Loading palette nodes
14 Sep 08:01:40 - [warn] rpi-gpio : Raspberry Pi specific node set inactive
14 Sep 08:01:43 - [error] Failed to start server:
14 Sep 08:01:43 - [error] Error: EACCES: permission denied, rename '/data/.config.json' -> '/data/.config.json.backup'
    at Object.renameSync (fs.js:598:3)
    at Object.writeFile (/usr/src/node-red/node_modules/@node-red/runtime/lib/storage/localfilesystem/util.js:84:20)
    at Object.saveSettings (/usr/src/node-red/node_modules/@node-red/runtime/lib/storage/localfilesystem/settings.js:52:21)
    at Object.saveSettings (/usr/src/node-red/node_modules/@node-red/runtime/lib/storage/index.js:117:38)
    at Object.set (/usr/src/node-red/node_amodules/@node-red/runtime/lib/settings.js:95:28)
    at Object.saveNodeList (/usr/src/node-red/node_modules/@node-red/registry/lib/registry.js:127:25)
    at /usr/src/node-red/node_modules/@node-red/registry/lib/loader.js:299:29
    at tryCatchReject (/usr/src/node-red/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/usr/src/node-red/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/usr/src/node-red/node_modules/when/lib/makePromise.js:592:4)

```

**Comment by mauog** [comment]
@fightforlife 
> I just tried your image as a dropin replacement for the rpi variant in docker compose.

> It doesnt seem to be fully compatible (permission problem):

I managed to run the continue fine.
I had yours same problem but I solved it forcing the UID and GID mapping in docker-compose file.
The container uses a 1001:1001 users which needs to be re-mapped to the owner of your persistent data directory. 
My persistent directory is owned by pi user (1000:1000) so I remapped it into docker-compose 

> user: 1000:1000

```
nodered1:
    image: raymondmm/node-red:latest
    container_name: nodered1
    network_mode: host
    environment:
      - TZ=Europe/Rome
    ports:
      - "1880:1880"
    volumes:
      - /storage/brick1/nodered:/data
    user: 1000:1000
    restart: always

```

Now it works like a charm :)

**Comment by RaymondMouthaan** [comment]
@fightforlife, thank you for testing, I have been trying your compose file as well, i had to disable the block devices, because i don't have them. Find below the node-red startup log, which seems to run fine.

```
version: "2"

services:

  nodered:
    image: raymondmm/node-red:latest
    #image: nodered/node-red-docker:rpi-v8
    container_name: nodered
    
    #Needed for WoL
    network_mode: "host" 
    #ports:
    #  - "9001:1880/tcp"
    
    restart: always
    volumes:
      - nodered_config:/data
      - nodered_cgroup:/sys/fs/cgroup
      - /sys:/sys
    #devices:
      #- "/dev/ttyUSB0:/dev/ttyUSB0"
      #- "/dev/ttyS0:/dev/ttyS0"
      #- "/dev/ttyS1:/dev/ttyS1"
      #- "/dev/ttyS2:/dev/ttyS2"
      #- "/dev/gpiochip0:/dev/gpiochip0"
      #- "/dev/gpiochip1:/dev/gpiochip1"
      #- "/dev/i2c-1:/dev/i2c-1"
      #- "/dev/i2c-2:/dev/i2c-2"
      #- "/dev/i2c-3:/dev/i2c-3"
      #- "/dev/i2c-4:/dev/i2c-4"
    # group_add:
    #   - dialout
    # dns: 
    #   - 192.168.1.4
    #   - 192.168.1.3
    #   - 192.168.1.2
    #   - 192.168.1.1

volumes:
  nodered_config:
  nodered_cgroup:

```

Node-red startup log:
```
nodered    | 
nodered    | > node-red-docker@1.0.0 start /usr/src/node-red
nodered    | > node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"
nodered    | 
nodered    | 14 Sep 08:22:05 - [info] 
nodered    | 
nodered    | Welcome to Node-RED
nodered    | ===================
nodered    | 
nodered    | 14 Sep 08:22:06 - [info] Node-RED version: v0.20.8
nodered    | 14 Sep 08:22:06 - [info] Node.js  version: v10.16.3
nodered    | 14 Sep 08:22:06 - [info] Linux 4.19.58-v7+ arm LE
nodered    | 14 Sep 08:22:07 - [info] Loading palette nodes
nodered    | 14 Sep 08:22:11 - [info] Settings file  : /data/settings.js
nodered    | 14 Sep 08:22:11 - [info] Context store  : 'default' [module=memory]
nodered    | 14 Sep 08:22:11 - [info] User directory : /data
nodered    | 14 Sep 08:22:11 - [warn] Projects disabled : editorTheme.projects.enabled=false
nodered    | 14 Sep 08:22:11 - [info] Flows file     : /data/flows.json
nodered    | 14 Sep 08:22:11 - [info] Creating new flow file
nodered    | 14 Sep 08:22:11 - [warn] 
nodered    | 
nodered    | ---------------------------------------------------------------------
nodered    | Your flow credentials file is encrypted using a system-generated key.
nodered    | 
nodered    | If the system-generated key is lost for any reason, your credentials
nodered    | file will not be recoverable, you will have to delete it and re-enter
nodered    | your credentials.
nodered    | 
nodered    | You should set your own key using the 'credentialSecret' option in
nodered    | your settings file. Node-RED will then re-encrypt your credentials
nodered    | file using your chosen key the next time you deploy a change.
nodered    | ---------------------------------------------------------------------
nodered    | 
nodered    | 14 Sep 08:22:11 - [info] Server now running at http://127.0.0.1:1880/
nodered    | 14 Sep 08:22:11 - [info] Starting flows
nodered    | 14 Sep 08:22:11 - [info] Started flows
```

Like @mauog said, user: 1000:1000 could do the trick, in his case the persistent volume is owned by pi (1000:1000), but in your case thats unclear, perhaps `nodered_config ` and `nodered_cgroup ` are owned by pi user as well? In side the container, node-red runs with the node-red user, which has uid 1001 and gid 1001, possibly your volumes have 1000:1000 as owner, thats why the node-red user has no permissions to rename `/data/.config.json' to `/data/.config.json.backup'.

Hope this helps.

Greets,
Ray
