### ISSUE TITLE
Publish time-out: Max size of nodes?

### ISSUE THREAD

**Issue by VincentSC** [node-red/node-red-docker#305]
There seems to be a maximum number of nodes that can be deployed, and it seems to only happens in Docker.

This is an issue that was originally reported by @hspjanssen. https://github.com/node-red/node-red/issues/3050 - please read that issue to understand the problem - it also has a few videos that explain the problem quite well. He migrated away from Docker and the problem disappeared. This is the main reason I put this issue here now.

For me personally, there are not just 47 nodes, but a few hundred nodes. Difference is that I have a more recent version. I also found that the problem is there when doing only a partial deployment - maybe a hint?

When I do `docker logs -f nodered` I see literally nothing when doing a deployment.

From Portainer:

Name | Setting
-- | --
LETSENCRYPT_HOST | _host_
NODE_PATH | /usr/src/node-red/node_modules:/data/node_modules
NODE_RED_VERSION | v2.1.3
NODE_VERSION | 14.18.1
PATH | /usr/src/node-red/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
TZ | Europe/Amsterdam
VIRTUAL_HOST | _host_
VIRTUAL_PORT | 1880
YARN_VERSION | 1.22.15

Dockerfile:
```
FROM nodered/node-red:latest
# Possibly better solutions for `USER root` at: https://stackoverflow.com/questions/50727783/alpine-docker-error-unable-to-lock-database-permission-denied-error-failed-to
USER root
RUN echo Installing additional packages
RUN apk add ipmitool

USER node-red
```

docker-compose:

```
version: "3"

services:
  nodered:
#    image: nodered/node-red:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
      - VIRTUAL_PORT=1880
    volumes:
      - ./volumes/data:/data
    container_name: ${COMPOSE_PROJECT_NAME}
    hostname: ${COMPOSE_PROJECT_NAME}.local
    depends_on:
       - mosquitto

  mosquitto:
    image: eclipse-mosquitto:1.6.15
    restart: unless-stopped
    hostname: mosquitto

networks:
  default:
    external:
      name: nginx-proxy
```

There is jwilder's nginx-proxy to handle https, with `client_max_body_size 0;` - it is tested to work with other dockers. Not sure if @hspjanssen had a reverse proxy in place, but I don't think this is the cause of the problem.
