### ISSUE TITLE
Crashing on RPi3 armv7l after latest build

### ISSUE THREAD

**Issue by thalesmaoa** [node-red/node-red-docker#395]
### What are the steps to reproduce?
Run latest image on a 32bit buster Raspberry Pi 3 armv7l.

### What happens?
```
nodered-casa  | 18 Nov 22:35:16 - [info] 
nodered-casa  | 
nodered-casa  | Welcome to Node-RED
nodered-casa  | ===================
nodered-casa  | 
nodered-casa  | 18 Nov 22:35:16 - [info] Node-RED version: v3.1.0
nodered-casa  | 18 Nov 22:35:16 - [info] Node.js  version: v16.20.2
nodered-casa  | 18 Nov 22:35:16 - [info] Linux 5.10.103-v7+ arm LE
nodered-casa  | 18 Nov 22:35:18 - [info] Loading palette nodes
nodered-casa  | 
nodered-casa  | 
nodered-casa  | #
nodered-casa  | # Fatal error in , line 0
nodered-casa  | # unreachable code
nodered-casa  | #
nodered-casa  | #
nodered-casa  | #
nodered-casa  | #FailureMessage Object: 0x7555075c
nodered-casa  | ./entrypoint.sh: line 14:     7 Trace/breakpoint trap   (core dumped) /usr/local/bin/node $NODE_OPTIONS node_modules/node-red/red.js --userDir /data $FLOWS "${@}"
nodered-casa exited with code 133
```

### Please tell us about your environment:

```
$ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
$ uname -a
Linux rasp 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux
```

The problem seems to emerged from the latest image (22 days ago). I wasn`t able to identify the before lastest to test. With some guidance, I can test.

### Extra

If I add env variable, it crashes as well:

```
services:
  nodered-casa:
    image: nodered/node-red:latest
    container_name: nodered-casa
    restart: no
    #group_add: 
    #  - dialout
    #devices:
    #  - "/dev/ttyAMA0:/dev/ttyAMA0"
    ports:
      - '1881:1880'
    volumes:
      - ./data:/data
    environment:
      - TZ=America/Sao_Paulo
      - NODE_OPTIONS="--max_old_space_size=256"
    logging:
      options:
        max-size: "100m"
```

```
nodered-casa  | node:internal/modules/cjs/loader:1031
nodered-casa  |   throw err;
nodered-casa  |   ^
nodered-casa  | 
nodered-casa  | Error: Cannot find module '/usr/src/node-red/"--max_old_space_size=256"'
nodered-casa  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
nodered-casa  |     at Function.Module._load (node:internal/modules/cjs/loader:873:27)
nodered-casa  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
nodered-casa  |     at node:internal/main/run_main_module:22:47 {
nodered-casa  |   code: 'MODULE_NOT_FOUND',
nodered-casa  |   requireStack: []
nodered-casa  | }
nodered-casa exited with code 1
```

**Comment by Paraphraser** [comment]
You could try either of the following

```
image: nodered/node-red:3.0.2
image: nodered/node-red:2.2
```

See also [DockerHub](https://hub.docker.com/r/nodered/node-red/tags?page=1&ordering=last_updated) - you need to go to the second page to find older images.

**Comment by thalesmaoa** [comment]
Thx @Paraphraser 

I confirm that Imdoes work for older version:

```
services:
  nodered-casa:
    #image: nodered/node-red:latest
    image: nodered/node-red:3.0.2
    container_name: nodered-casa
    restart: no
    #group_add: 
    #  - dialout
    #devices:
    #  - "/dev/ttyAMA0:/dev/ttyAMA0"
    ports:
      - '1881:1880'
    volumes:
      - ./data:/data
    environment:
      - TZ=America/Sao_Paulo
      - NODE_OPTIONS=--max_old_space_size=256
    logging:
      options:
        max-size: "100m"
        max-file: "3"
```
