### ISSUE TITLE
Docker volume mapped /data volume uses irritating UID/GID

### ISSUE THREAD

**Issue by wjdp** [node-red/node-red-docker#82]
I have a server with a few containers, most I can configure the UID/GID of the container's run user using environment variables `PUID` and `PGID` (or advertise another variable for this purpose).

The node-red container runs as a user with UID 1001 which maps on my host to a user with another purpose. Docker seems to have little support for addressing this issue. 

Is there a method to force the UID of the container to another number?

**Comment by dawidcrivelli** [comment]
Sure, you can run `docker run -u UID`, for example zero for root

**Comment by AnderssonPeter** [comment]
Is there someway to do this with docker compose?

**Comment by dawidcrivelli** [comment]
@AnderssonPeter, yes, you can add a `user` line in the instance in the docker-compose file: https://medium.com/redbubble/running-a-docker-container-as-a-non-root-user-7d2e00f8ee15

**Comment by rcarmo** [comment]
I stumbled upon this while looking for close matches to #109, so here's a `docker-compose` snippet that matches the current user by using the `UID` environment variable:

```yaml
node-red:
        hostname: flows
        image: "nodered/node-red-docker:0.20.5-slim-v10" # https://hub.docker.com/r/nodered/node-red-docker/tags
        restart: always
        user: ${UID} # this needs to be set so that node-red can match filesystem UIDs
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /dev/rtc:/dev/rtc:ro
            - ${HOME}/.config/node-red:/data
        ports:
           - "1880:1880"
```

Hope it's useful.
