### ISSUE TITLE
-e TZ being ignored

### ISSUE THREAD

**Issue by danmandle** [node-red/node-red-docker#92]
### What are the steps to reproduce?
```
  node-red:
    container_name: node-red
    depends_on:
      - home-assistant
    image: nodered/node-red-docker:v8
    ports:
      - "1880"
    restart: unless-stopped
    environment:
      - TZ="America/Denver"
    volumes:
      - /var/docker/node-red:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
```

```
danmandle@jade:/var/docker/traefik$ date
Tue Dec 11 22:28:36 MST 2018
danmandle@jade:/var/docker/traefik$ docker exec node-red date
Wed Dec 12 05:29:00  2018
```

### What happens?
Timezone in container is UTC

### What do you expect to happen?
Timezone should be set from `TZ` environment variable.

### Please tell us about your environment:

Docker image `nodered/node-red-docker:v8`
